In [9]:
from sklearn import datasets
from scipy.spatial import distance
import numpy as np

iris = datasets.load_iris()
X = iris.data

print(np.mean(X, axis=0))
print(np.std(X, axis=0))

[5.84333333 3.05733333 3.758      1.19933333]
[0.82530129 0.43441097 1.75940407 0.75969263]


$d(\mathbf{p},\mathbf{q})={\sqrt {(\mathbf{p}-\mathbf{q})^{T}\mathbf{\Sigma}^{-1}(\mathbf{p}-\mathbf{q})}}$

In [10]:
x1 = X[0,:]
x2 = X[1,:]

S = np.cov(X.T)
IS = np.linalg.inv(S)

print(x1)
print(x2)
print(IS)

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[[ 10.31469875  -6.71318923  -7.31448253   5.739951  ]
 [ -6.71318923  11.05841725   6.48058913  -6.17093237]
 [ -7.31448253   6.48058913  10.03167858 -14.5137665 ]
 [  5.739951    -6.17093237 -14.5137665   27.69363502]]


$\mathbf{a} = \mathbf{p} -\mathbf{q} = (q_{1}-p_{1},q_{2}-p_{2},\cdots ,q_{n}-p_{n})$

$d(\mathbf{p},\mathbf{q})={\sqrt {\mathbf{a}^{T}\mathbf{\Sigma}^{-1}\mathbf{a}}}$

$d(\mathbf{p},\mathbf{q}) = \sqrt{{\begin{bmatrix}a_{1}&a_{2}&...&a_{n}\end{bmatrix}}\begin{bmatrix}\sigma_{11}&\sigma_{12}&\cdots &\sigma_{1p}\\\sigma_{21}&\sigma_{22}&\cdots &\sigma_{2n}\\\vdots &\vdots &\ddots &\vdots \\\sigma_{n1}&\sigma_{n2}&\cdots &\sigma_{nn}\\\end{bmatrix}{\begin{bmatrix}a_{1}\\a_{2}\\...\\a_{n}\end{bmatrix}}}$

In [11]:
def mahalanobisDot(p,q,V):
    r = (p-q) @ V @ (p-q)
    return np.sqrt(r)

mahalanobisDot(x1,x2,IS)

1.35445723989668

In [12]:
def mahalanobisScipy(p,q,v):
    return distance.mahalanobis(p,q,v)

mahalanobisScipy(x1,x2,IS)

1.35445723989668

## Mahalanobis distance and normalized Euclidean distance are equivalents when the data are fully independent (i.e. no covariance between features) 

In [13]:
S = np.cov(X.T)
print(S)

IS = np.identity(4)*S
IS = np.linalg.inv(IS)
print(IS)

print(distance.mahalanobis(x1,x2,IS))
print(distance.seuclidean(x1,x2,np.diag(S)))

[[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]
[[1.45837751 0.         0.         0.        ]
 [0.         5.26372809 0.         0.        ]
 [0.         0.         0.32089565 0.        ]
 [0.         0.         0.         1.72115184]]
1.1722913980470526
1.1722913980470526


## Mahalanobis distance and Euclidean distance are equivalents when the data are fully independent (i.e. no covariance between features) and are standardized by z-score (i.e. unitary variance of features)

In [14]:
X_std = (X - np.mean(X, axis=0))
X_std = (X_std / np.std(X, axis=0))

print(np.mean(X_std, axis=0))
print(np.std(X_std, axis=0))

S = np.cov(X_std.T, ddof=0)
print(S)

IS = np.identity(4)*S
IS = np.linalg.inv(IS)
print(IS)

print(distance.mahalanobis(x1,x2,IS))
print(distance.euclidean(x1,x2))

[-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15]
[1. 1. 1. 1.]
[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
0.5385164807134505
0.5385164807134502


In [15]:
1 / 5

0.2

In [16]:
1 * 0.2

0.2