In [215]:
from sklearn import datasets
from scipy.spatial import distance
import numpy as np

iris = datasets.load_iris()
X = iris.data

print(np.mean(X, axis=0))
print(np.std(X, axis=0))

[5.84333333 3.05733333 3.758      1.19933333]
[0.82530129 0.43441097 1.75940407 0.75969263]


$d(\mathbf{p},\mathbf{q})={\sqrt {\sum _{i=1}^{n}{(p_{i}-q_{i})^{2} \over \sigma _{i}^{2}}}}$

In [216]:
x1 = X[0,:]
x2 = X[1,:]

v = np.var(X, axis=0)

print(x1)
print(x2)
print(v)

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[0.68112222 0.18871289 3.09550267 0.57713289]


In [217]:
def seuclideanScratch(p,q,v):
    return np.sqrt(np.sum(((p-q)**2 / v), axis=0))

seuclideanScratch(x1,x2,v)

1.1762186834130144

In [218]:
def seuclideanScipy(p,q,v):
    return distance.seuclidean(p,q,v)

seuclideanScipy(x1,x2,v)

1.1762186834130146

In [220]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X)
X = sc.transform(X)

print(np.mean(X, axis=0))
print(np.std(X, axis=0))

[-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15]
[1. 1. 1. 1.]


In [221]:
x1 = X[0,:]
x2 = X[1,:]

v = np.var(X, axis=0)

print(x1)
print(x2)
print(v)

[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
[-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
[1. 1. 1. 1.]


$d(\mathbf{p},\mathbf{q})=\sqrt{ \sum_{i=1}^{n} \frac{(p_{i}-q_{i})^2}{1} }$



In [222]:
seuclideanScratch(x1,x2,v)

1.1762186834130153

In [223]:
seuclideanScipy(x1,x2,v)

1.1762186834130153

In [225]:
print(distance.euclidean(x1,x2))
print(distance.seuclidean(x1,x2,v))

1.1762186834130146
1.1762186834130153


$d(\mathbf{p},\mathbf{q})={\sqrt {(\mathbf{p}-\mathbf{q})^{T}\mathbf{S}^{-1}(\mathbf{p}-\mathbf{q})}}$

In [226]:
X = iris.data

x1 = X[0,:]
x2 = X[1,:]

S = np.cov(X.T, ddof=0)
S = np.identity(4)*S

print(x1)
print(x2)
print(S)

print(np.var(X, axis=0))

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[[ 0.68112222 -0.          0.          0.        ]
 [-0.          0.18871289 -0.         -0.        ]
 [ 0.         -0.          3.09550267  0.        ]
 [ 0.         -0.          0.          0.57713289]]
[0.68112222 0.18871289 3.09550267 0.57713289]


$\mathbf{a} = \mathbf{p} -\mathbf{q} = (q_{1}-p_{1},q_{2}-p_{2},\cdots ,q_{n}-p_{n})$

$d(\mathbf{p},\mathbf{q})={\sqrt {\mathbf{a}^{T}\mathbf{S}^{-1}\mathbf{a}}}$

$d(\mathbf{p},\mathbf{q}) = \sqrt{{\begin{bmatrix}a_{1}&a_{2}&...&a_{n}\end{bmatrix}}\begin{bmatrix}s_{11}&s_{12}&\cdots &s_{1p}\\s_{21}&s_{22}&\cdots &s_{2n}\\\vdots &\vdots &\ddots &\vdots \\s_{n1}&s_{n2}&\cdots &s_{nn}\\\end{bmatrix}{\begin{bmatrix}a_{1}\\a_{2}\\...\\a_{n}\end{bmatrix}}}$

In [227]:
a = x1-x2
a

array([0.2, 0.5, 0. , 0. ])

In [228]:
r = np.matmul(a,np.linalg.inv(S))
r

array([0.29363306, 2.64952756, 0.        , 0.        ])

In [229]:
r3= np.matmul(r,np.transpose(a))
np.sqrt(r3)

1.1762186834130144

In [231]:
def seuclideanDot(p,q,V):
    V = np.linalg.inv(V)
    r = (p-q) @ V @ (p-q)
    return np.sqrt(r)

seuclideanDot(x1,x2,S)

1.1762186834130144

In [232]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X)
X = sc.transform(X)

print(np.mean(X, axis=0))
print(np.std(X, axis=0))

[-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15]
[1. 1. 1. 1.]


In [233]:
x1 = X[0,:]
x2 = X[1,:]

S = np.cov(X.T, ddof=0)
S = np.identity(4)*S


print(x1)
print(x2)
print(S)

[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
[-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
[[ 1. -0.  0.  0.]
 [-0.  1. -0. -0.]
 [ 0. -0.  1.  0.]
 [ 0. -0.  0.  1.]]


In [234]:
seuclideanDot(x1,x2,S)

1.1762186834130153

In [235]:
print(seuclideanDot(x1,x2,np.identity(4)))
print(distance.seuclidean(x1,x2,np.diag(np.identity(4))))
print(distance.euclidean(x1,x2))

1.1762186834130146
1.1762186834130146
1.1762186834130146
